API-Only: false
UseClanColors: true
AlwaysUpperCaseClanTag: false
new-display-name: '&e<[%CLAN_TAG%]&e> [%PLAYER_DISPLAY_NAME%]&r'
UseCache: false
CacheTimeInSeconds: 360
PlaceholderCustomDesign:
  Placeholder: '&e<[%CLAN_TAG%]&e> '
  OnEmpty: ''
  ClanName:
    Placeholder: '&e<[%CLAN_NAME%]&e> '
    OnEmpty: ''