API-Only: false
UseClanColors: true
new-display-name: '&e<[%CLAN_TAG%]&e> [%PLAYER_DISPLAY_NAME%]&r'
PlaceholderCustomDesign:
  Placeholder: '&e<[%CLAN_TAG%]&e> '
  OnEmpty: ''
  ClanName:
    Placeholder: '&e<[%CLAN_NAME%]&e> '
    OnEmpty: ''