main: de.simonsator.partyandfriends.spigot.clans.ClansMainSpigot
name: Clans-Spigot-Part
version: ${project.version}
author: Simonsator
depend: [FriendsAPIForPartyAndFriends]
softdepend: [MVdWPlaceholderAPI, PlaceholderAPI]